USE `crowdsource_db`;

CREATE TABLE IF NOT EXISTS `categories` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `users` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `login` VARCHAR(255) NOT NULL UNIQUE,
    `name` VARCHAR(64),
    `level` INTEGER,
    `password` CHAR(32) NOT NULL,
    `photo_path` VARCHAR(255),
    `role` TINYINT NOT NULL CHECK (`role` IN (0, 1)),
    PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `images` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
	`path` VARCHAR(255),
	`category` INTEGER,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`category`)
    REFERENCES `categories` (`id`)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `favorites` (
	`user_id` INTEGER NOT NULL,
	`category_id` INTEGER NOT NULL,
	FOREIGN KEY (`user_id`)
	REFERENCES `users` (`id`)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
	FOREIGN KEY (`category_id`)
	REFERENCES `categories` (`id`)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `settings` (
	`settings_name` VARCHAR(64) NOT NULL,
	`settings_value` VARCHAR(255) NOT NULL
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `blacklist` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
	`login` VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;




